/**
 * viralPayloadFormatter.ts - Viral Distribution Content Generator
 * 
 * Converts demo results into shareable formats:
 * - Tweet-ready format
 * - Markdown share card
 * - "Copy this post" block
 * 
 * Makes every demo result instantly shareable.
 */

import { DemoSession, DemoSummary } from './demoLinkGenerator';

export interface ViralPayload {
  // Social formats
  tweet: string;
  linkedin: string;
  
  // Technical formats
  markdown: string;
  html: string;
  
  // Meta
  title: string;
  description: string;
  imageText: string;
  
  // Pre-built CTAs
  ctas: {
    primary: string;
    secondary: string;
  };
}

export interface ShareCard {
  text: string;
  background: string;
  foreground: string;
  accent: string;
}

/**
 * ViralPayloadFormatter - Turns demo results into viral content
 * 
 * Distribution strategy:
 * 1. User sees impressive savings
 * 2. One-click generates shareable content
 * 3. Content optimized for each platform
 * 4. Every share drives new users to demo
 */
export function generateViralPayload(session: DemoSession): ViralPayload {
  const s = session.summary;
  const scenario = session.scenario;

  // Core message: You could have saved X% on your AI costs
  const savingsPercent = Math.round(s.savingsPercent);
  const savingsAmount = formatCurrency(s.totalSaved);

  return {
    tweet: generateTweet(s, scenario, savingsPercent, savingsAmount),
    linkedin: generateLinkedIn(s, scenario, savingsPercent, savingsAmount),
    markdown: generateMarkdown(s, scenario, session.id),
    html: generateHTML(s, scenario, session.id),
    title: `I prevented $${s.totalSaved.toFixed(0)} in AI cost overruns`,
    description: `${s.blocked} wasteful requests blocked, ${savingsPercent}% cost reduction`,
    imageText: `-${savingsPercent}% AI COSTS`,
    ctas: {
      primary: `Prevent AI cost explosions:`,
      secondary: `Try the interactive demo →`,
    },
  };
}

/**
 * Generate tweet-ready text
 * Under 280 characters with emoji
 */
export function generateTweet(
  summary: DemoSummary,
  scenario: { name: string; agentType: string },
  savingsPercent: number,
  savingsAmount: string
): string {
  const lines = [
    `🛡️ Just ran the "${scenario.name}" demo:`,
    ``,
    `${savingsPercent}% cost reduction`,
    `${summary.blocked} wasteful requests blocked`,
    `${savingsAmount} saved in 5 min simulation`,
    ``,
    `AI cost explosions are real 💸`,
    `This stops them before they start`,
    ``,
    `Try it:`,
  ];

  return lines.join('\n');
}

/**
 * Generate LinkedIn post format
 * Professional, story-driven
 */
export function generateLinkedIn(
  summary: DemoSummary,
  scenario: { name: string; agentType: string; description: string },
  savingsPercent: number,
  savingsAmount: string
): string {
  return `I just discovered a tool that prevents AI cost explosions in production.

Ran the "${scenario.name}" demo—basically simulates a ${scenario.agentType} agent going rogue and making redundant API calls.

Results in 5 minutes:
• ${summary.totalRequests} requests analyzed
• ${summary.blocked} wasteful calls blocked
• ${savingsPercent}% cost reduction
• ${savingsAmount} in hypothetical savings

The problem: When AI agents get stuck in loops or duplicate work, costs spiral fast. I've seen teams burn through monthly budgets in days.

The solution: This firewall sits between your app and OpenAI, detecting expensive patterns before they hit your bill.

If you're running AI in production, worth a look.

#AI #CostOptimization #LLM #ProductionAI`;
}

/**
 * Generate Markdown share card
 * For GitHub, READMEs, documentation
 */
export function generateMarkdown(
  summary: DemoSummary,
  scenario: { name: string },
  sessionId: string
): string {
  return `## 🛡️ AI Cost Explosion Prevention Demo

**Scenario:** ${scenario.name}

### Results

| Metric | Value |
|--------|-------|
| Total Requests | ${summary.totalRequests} |
| Blocked | ${summary.blocked} 💰 |
| Throttled | ${summary.throttled} |
| Allowed | ${summary.allowed} |
| **Cost Without Protection** | **${formatCurrency(summary.totalCostBefore)}** |
| **Cost With Firewall** | **${formatCurrency(summary.totalCostAfter)}** |
| **Money Saved** | **${formatCurrency(summary.totalSaved)}** (${summary.savingsPercent.toFixed(1)}%) |

### What This Means

In this simulation, the AI Cost Explosion Prevention Layer detected and blocked expensive runaway patterns—saving ${summary.savingsPercent.toFixed(0)}% of the total API costs.

In production, this prevents:
- Runaway agent loops
- Uncontrolled API spending  
- Cost spikes from redundant calls

[View Full Demo](https://ai-firewall.io/demo/${sessionId})

---

*Generated by AI Cost Explosion Prevention Layer*`;
}

/**
 * Generate HTML embeddable widget
 * For blogs, dashboards, etc.
 */
export function generateHTML(
  summary: DemoSummary,
  scenario: { name: string },
  sessionId: string
): string {
  return `<div style="
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 500px;
    border: 2px solid #667eea;
    border-radius: 12px;
    padding: 24px;
    background: linear-gradient(135deg, #f5f7fa 0%, #e4e8f0 100%);
  ">
  <div style="
    display: flex;
    align-items: center;
    margin-bottom: 16px;
  ">
    <span style="font-size: 2rem; margin-right: 12px;">🛡️</span>
    <div>
      <h3 style="margin: 0; color: #667eea;">AI Cost Explosion Prevention</h3>
      <p style="margin: 4px 0 0; color: #666; font-size: 0.9rem;">${scenario.name} Demo</p>
    </div>
  </div>
  
  <div style="
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 16px;
    margin-bottom: 20px;
  ">
    <div style="text-align: center; padding: 12px; background: white; border-radius: 8px;">
      <div style="font-size: 1.8rem; font-weight: bold; color: #dc3545;">${formatCurrency(summary.totalCostBefore)}</div>
      <div style="font-size: 0.8rem; color: #888;">Without Protection</div>
    </div>
    <div style="text-align: center; padding: 12px; background: white; border-radius: 8px;">
      <div style="font-size: 1.8rem; font-weight: bold; color: #28a745;">${formatCurrency(summary.totalCostAfter)}</div>
      <div style="font-size: 0.8rem; color: #888;">With Firewall</div>
    </div>
  </div>
  
  <div style="
    text-align: center;
    padding: 16px;
    background: #667eea;
    color: white;
    border-radius: 8px;
    margin-bottom: 16px;
  ">
    <div style="font-size: 1.5rem; font-weight: bold;">${formatCurrency(summary.totalSaved)} Saved</div>
    <div style="opacity: 0.9;">${summary.savingsPercent.toFixed(1)}% cost reduction</div>
  </div>
  
  <div style="
    display: flex;
    justify-content: space-around;
    font-size: 0.9rem;
    color: #666;
  ">
    <span>🚫 ${summary.blocked} blocked</span>
    <span>✅ ${summary.allowed} allowed</span>
    <span>⏱️ ${summary.throttled} throttled</span>
  </div>
  
  <a href="https://ai-firewall.io/demo/${sessionId}" style="
    display: block;
    text-align: center;
    margin-top: 16px;
    padding: 12px;
    background: #667eea;
    color: white;
    text-decoration: none;
    border-radius: 8px;
    font-weight: 600;
  ">View Full Demo →</a>
</div>`;
}

/**
 * Generate a "Copy to Clipboard" block
 * Pre-formatted for instant sharing
 */
export function generateCopyBlock(session: DemoSession): string {
  const payload = generateViralPayload(session);
  
  return `═══════════════════════════════════════
${payload.title}
═══════════════════════════════════════

${payload.tweet}

${payload.markdown}

${payload.html}

═══════════════════════════════════════
Share this demo: https://ai-firewall.io/demo/${session.id}
═══════════════════════════════════════`;
}

/**
 * Generate social card metadata
 * For Open Graph, Twitter Cards, etc.
 */
export function generateSocialCardMeta(session: DemoSession): {
  ogTitle: string;
  ogDescription: string;
  ogImage: string;
  twitterCard: string;
  twitterTitle: string;
  twitterDescription: string;
} {
  const s = session.summary;
  
  return {
    ogTitle: `Saved ${formatCurrency(s.totalSaved)} (${s.savingsPercent.toFixed(0)}%) with AI Cost Firewall`,
    ogDescription: `${s.blocked} wasteful requests blocked in "${session.scenario.name}" demo. Prevent AI cost explosions before they happen.`,
    ogImage: `https://ai-firewall.io/demo/${session.id}/preview.png`,
    twitterCard: 'summary_large_image',
    twitterTitle: `🛡️ AI Cost Explosion Prevention`,
    twitterDescription: `${s.savingsPercent.toFixed(0)}% cost reduction • ${formatCurrency(s.totalSaved)} saved • ${s.blocked} blocked`,
  };
}

/**
 * Generate email-ready format
 * For newsletter sharing
 */
export function generateEmailContent(session: DemoSession): {
  subject: string;
  body: string;
} {
  const s = session.summary;
  
  return {
    subject: `Demo Results: ${s.savingsPercent.toFixed(0)}% AI Cost Reduction`,
    body: `Hi there,

I just ran the AI Cost Explosion Prevention demo and wanted to share the results.

SCENARIO: ${session.scenario.name}
${session.scenario.description}

RESULTS:
- Total Requests: ${s.totalRequests}
- Blocked (Cost Saved): ${s.blocked}
- Cost Without Protection: ${formatCurrency(s.totalCostBefore)}
- Cost With Firewall: ${formatCurrency(s.totalCostAfter)}
- MONEY SAVED: ${formatCurrency(s.totalSaved)} (${s.savingsPercent.toFixed(1)}%)

This tool prevents runaway AI agents from draining your API budget. Worth checking out if you're using LLMs in production.

View the full demo: https://ai-firewall.io/demo/${session.id}

Best,`,
  };
}

// Helper function
function formatCurrency(amount: number): string {
  return '$' + amount.toFixed(2);
}

// Convenience exports
export {
  formatCurrency,
};
